# Independent build tree: main --clean-first cannot remove these libraries.
if(NOT WIN32 OR NOT MSVC)
    message(FATAL_ERROR "Prebuilt PC dependencies require Windows/MSVC")
endif()
option(MIKAN_ENABLE_NRD "Enable native Vulkan NRD denoisers" ON)
if(CMAKE_CONFIGURATION_TYPES)
    message(FATAL_ERROR "Use the x64-release/x64-debug single-config presets for the PC dependency package")
endif()
if(NOT CMAKE_MSVC_RUNTIME_LIBRARY)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
endif()
string(SHA256 fingerprint "${CMAKE_CXX_COMPILER}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_SIZEOF_VOID_P}|${CMAKE_BUILD_TYPE}|${CMAKE_MSVC_RUNTIME_LIBRARY}|${CMAKE_CXX_FLAGS}|${CMAKE_C_FLAGS}|${MIKAN_ENABLE_NRD}")
string(SUBSTRING "${fingerprint}" 0 12 key)
set(MIKAN_PC_DEPENDENCY_DIR "${CMAKE_SOURCE_DIR}/out/pc-dependencies/${CMAKE_BUILD_TYPE}-${key}" CACHE PATH "Isolated prebuilt PC dependency directory" FORCE)
set(package "${CMAKE_SOURCE_DIR}/cmake/pc-dependencies")
message(STATUS "PC dependency package: ${MIKAN_PC_DEPENDENCY_DIR}")
option(MIKAN_REBUILD_PC_DEPENDENCIES "Refresh the isolated dependency package" OFF)
set(package_missing FALSE)
foreach(name JoltPhysics Box2D msdfgen ImGui)
    if(NOT EXISTS "${MIKAN_PC_DEPENDENCY_DIR}/lib/${name}.lib")
        set(package_missing TRUE)
    endif()
endforeach()
if(MIKAN_ENABLE_NRD AND (NOT EXISTS "${MIKAN_PC_DEPENDENCY_DIR}/lib/NRD.lib" OR NOT EXISTS "${MIKAN_PC_DEPENDENCY_DIR}/lib/ShaderMakeBlob.lib"))
    set(package_missing TRUE)
endif()
if(package_missing OR MIKAN_REBUILD_PC_DEPENDENCIES)
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${package}" -B "${MIKAN_PC_DEPENDENCY_DIR}" -G Ninja
    "-DMIKAN_SOURCE_ROOT=${CMAKE_SOURCE_DIR}" "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
    "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}"
    "-DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}" "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
    "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}" "-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}"
    "-DMIKAN_ENABLE_NRD=${MIKAN_ENABLE_NRD}" RESULT_VARIABLE configured)
if(NOT configured EQUAL 0)
    message(FATAL_ERROR "PC dependency configuration failed")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${MIKAN_PC_DEPENDENCY_DIR}" --parallel 8 RESULT_VARIABLE built)
if(NOT built EQUAL 0)
    message(FATAL_ERROR "PC dependency build failed")
endif()
set(MIKAN_REBUILD_PC_DEPENDENCIES OFF CACHE BOOL "Refresh the isolated dependency package" FORCE)
endif()
foreach(name JoltPhysics Box2D msdfgen ImGui)
    add_library(${name} STATIC IMPORTED GLOBAL)
    set_target_properties(${name} PROPERTIES IMPORTED_LOCATION "${MIKAN_PC_DEPENDENCY_DIR}/lib/${name}.lib")
endforeach()
set_target_properties(JoltPhysics PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/dependencies/JoltPhysics")
set_target_properties(Box2D PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/dependencies/box2d/include")
set_target_properties(msdfgen PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/dependencies")
if(MIKAN_ENABLE_NRD)
    add_library(ShaderMakeBlob STATIC IMPORTED GLOBAL)
    set_target_properties(ShaderMakeBlob PROPERTIES IMPORTED_LOCATION "${MIKAN_PC_DEPENDENCY_DIR}/lib/ShaderMakeBlob.lib")
    add_library(NRD STATIC IMPORTED GLOBAL)
    set_target_properties(NRD PROPERTIES IMPORTED_LOCATION "${MIKAN_PC_DEPENDENCY_DIR}/lib/NRD.lib"
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/dependencies/NRD/Include"
        INTERFACE_COMPILE_DEFINITIONS "NRD_STATIC_LIBRARY=1" INTERFACE_LINK_LIBRARIES ShaderMakeBlob)
endif()
